name: Artifacts

on: push

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: echo "This is a test file this would be download" > testfile.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: testfile.txt
          retention-days: 7

  download-artifact:
    runs-on: ubuntu-latest
    needs: create-artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-artifact


      - name: print downloaded file
        run: cat testfile.txt


      