name: GitHub Actions Secrets print

on: workflow_dispatch

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    environment:
        name: production
        # url: https://example.com

        
    steps:
      - name: Print GitHub Secrets
        run: |
          echo "Secret 1: ${{ secrets.MY_SECRET }}"
          echo "Secret 2: ${{ secrets.S_SECRET }}"
          
        env:
          SECRET_1: ${{ secrets.MY_SECRET }}
          SECRET_2: ${{ secrets.S_SECRET }}