name: Steps variable

on: workflow_dispatch

jobs:
  print-steps-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set Step Variable
        id: step_variable
        run: |
          echo "variable=This is a step variable" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Print Steps Variable
        run: |
          echo "Step Variable: ${{ steps.step_variable.outputs.variable }}"
          echo "Date: ${{ steps.step_variable.outputs.date }}"

  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.variable }}
    steps:
      - name: Set Output in Job1
        id: step1
        run: |
          echo "variable=This is output from job1 step1" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Output from Job1
        run: echo "Output from job1 step1: ${{ needs.job1.outputs.output1 }}"
