name: steps variable


on: workflow_dispatch

jobs:
  print-steps-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Print Steps Variable
        run: |
          echo "Step Variable: ${{ steps.step_variable.outputs.variable }}"
          
      - name: Set Step Variable
        id: step_variable
        run: echo "::set-output name=variable::This is a step variable" 
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
        # This sets a variable that can be used in subsequent steps

  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.variable }}
    
    steps:
      id: step1
      run: echo "::set-output name=variable::This is output from job1 step1"
      

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      run: echo "Output from job1 step1: ${{ needs.job1.outputs.output1 }}"
        # This prints the output from job1 step1