name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

env:
  name: "gloria"

jobs:

env:
  var: "hello"


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print values 
        run: |
          echo "haii $name"
          echo "haii $var"
    
        
