name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

env:
  name: "gloria"   # Global environment variable
  

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      var: "hello"   # Job-level environment variable
    steps:
      - name: Print values (Deploy Job)
        run: |
          echo "haii $name"
          echo "haii $var"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print name (Print-Env Job)
        run: echo "Hello from $name"
        env:
          name: "sandra"  # Step-level environment variable
  
  job3:
    runs-on: windows-latest
    steps:
      - name: print default name (Windows Job)
        run: env
        