name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

env:
  name: "gloria"   # Global environment variable

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      var: "hello"   # Job-level environment variable
    steps:
      - name: Print values
        run: |
          echo "haii $name"
          echo "haii $var"

      
    
        
