name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

env:
  name: "gloria"   # Global environment variable

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      var: "hello"   # Job-level environment variable
    steps:
      - name: Print values (Deploy Job)
        run: |
          echo "haii $name"
          echo "haii $var"

  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print name (Print-Env Job)
        run: echo "Hello from $name"
        env:
          name: "sandra"  # Step-level environment variable